language: node_js
node_js:
- 0.1
before_install: npm install -g bower grunt-cli
install: npm install
before_script: bower install
deploy:
  provider: openshift
  user: mediamatik@seco.admin.ch
  password:
    secure: DF8beu6ZtmB6Z/xIAcwZ7jQCnopy7JX9SsoE/ljwDFm5bGSqW6gDFQ150sk3yBYyj5JCDON9EvBbSu5BxJKucjmX+HeQCATOwXGdTJcRSOTuC8IWEwN//RIrM3iKOeo32LUJSZbturjq+bllsR917SMsUsP++P77ehupXJzMfg4=
  app: ng
  domain: alvchegov
  on:
    repo: alv-ch-ng/demo
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git add --all
- git commit -am "Travis change"
